#!/bin/bash
#
# Backup Disk Usage Monitor
# Tracks backup directory size and sends alerts when thresholds are exceeded
#
# Features:
#   - Monitors backup directory size growth
#   - Tracks file count and compression statistics
#   - Alerts when approaching storage limits
#   - Stores historical usage data
#   - Predicts storage exhaustion based on growth rate
#   - Logs all monitoring data
#

# Note: Not using 'set -e' to allow script to continue even if JSON update fails
# Critical operations will explicitly check exit codes

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$(dirname "${SCRIPT_DIR}")")"
BACKUP_ROOT="${BASE_DIR}/backups"
LOG_DIR="${BASE_DIR}/logs"
MONITOR_LOG="${LOG_DIR}/backup-disk-monitor.log"
HISTORY_FILE="${BACKUP_ROOT}/monitor-history.json"

# Monitoring thresholds (in percentage)
WARN_THRESHOLD=75      # Alert when 75% full
CRITICAL_THRESHOLD=90  # Critical alert when 90% full

# Load .env if it exists for environment variables
if [ -f "${BASE_DIR}/.env" ]; then
    set +a
    source "${BASE_DIR}/.env"
    set -a
fi

# Email settings
EMAIL_ENABLED="${BACKUP_EMAIL_ENABLED:-true}"
EMAIL_RECIPIENT="${BACKUP_EMAIL:-admin@example.com}"
EMAIL_SUBJECT_PREFIX="[Maps Tracker Backup Disk Monitor]"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging functions
log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[${timestamp}] [${level}] ${message}" | tee -a "${MONITOR_LOG}"
}

log_info() {
    log "INFO" "$@"
    echo -e "${GREEN}[INFO]${NC} $@"
}

log_warn() {
    log "WARN" "$@"
    echo -e "${YELLOW}[WARN]${NC} $@"
}

log_error() {
    log "ERROR" "$@"
    echo -e "${RED}[ERROR]${NC} $@" >&2
}

# Send email notification
send_disk_notification() {
    local status=$1
    local details=$2

    if [ "$EMAIL_ENABLED" != "true" ]; then
        return 0
    fi

    local subject="${EMAIL_SUBJECT_PREFIX} ${status^^} - Action Required"

    local email_body="════════════════════════════════════════════════════════════════
DISK USAGE ALERT - Maps Tracker Backup System
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          $(hostname)
Environment:     Production
Alert Type:      Backup Storage Capacity Monitoring
Status:          ${status^^}
Timestamp:       $(date '+%Y-%m-%d %H:%M:%S')

WHAT THIS MEANS:
──────────────────────────────────────────────────────────────────
The backup storage partition is approaching or has exceeded safe
usage thresholds. If disk fills completely, new backups cannot be
created and database recovery capability will be lost.

STORAGE ALERT THRESHOLDS:
──────────────────────────────────────────────────────────────────
• WARNING:  75% full - Start monitoring/cleanup
• CRITICAL: 90% full - Immediate action required

CURRENT DISK STATUS:
──────────────────────────────────────────────────────────────────
${details}

IMMEDIATE ACTION REQUIRED (in order of priority):
──────────────────────────────────────────────────────────────────
1. Log into server $(hostname)

2. Check disk space immediately:
   df -h ${BACKUP_ROOT}

3. Review backup files:
   du -sh ${BACKUP_ROOT}/*

4. Manually compress older backups NOW:
   ${BASE_DIR}/scripts/backup/archive-old-backups.sh

5. Delete backups older than 180 days:
   find ${BACKUP_ROOT} -type f -name 'backup_*.sql' -mtime +180 -delete

6. Verify space was freed:
   df -h

IF STILL CRITICAL:
──────────────────────────────────────────────────────────────────
• Increase partition size (expand disk storage)
• Move old backups to archive storage
• Implement more aggressive retention policy
• Reduce backup frequency if acceptable

PREVENTION FOR FUTURE:
──────────────────────────────────────────────────────────────────
✓ Backups are automatically compressed after 30 days
✓ Backups older than 180 days are automatically deleted
✓ Disk monitoring runs daily at 3:30 AM
✓ Plan for storage growth in capacity planning

SUPPORT CONTACT:
──────────────────────────────────────────────────────────────────
Contact: System Administrator / DevOps Team
Priority: HIGH - Address within 24 hours
Log Location: /home/devnan/effective-guide/logs/backup-disk-monitor.log

════════════════════════════════════════════════════════════════
This is an automated monitoring alert from Maps Tracker backup system.
Generated by: Disk Usage Monitor"

    # Try using the SMTP relay script
    local SEND_EMAIL_SCRIPT="${BASE_DIR}/scripts/email/send-email.sh"
    if [ -f "${SEND_EMAIL_SCRIPT}" ]; then
        "${SEND_EMAIL_SCRIPT}" "$EMAIL_RECIPIENT" "$subject" "$email_body" 2>&1
        return $?
    fi

    # Fallback to mail command if available
    if command -v mail &> /dev/null || command -v mailx &> /dev/null; then
        local MAIL_CMD="mail"
        if command -v mailx &> /dev/null; then
            MAIL_CMD="mailx"
        fi
        echo "$email_body" | $MAIL_CMD -s "$subject" "$EMAIL_RECIPIENT" 2>&1
        return $?
    fi

    return 1
}

# Get backup directory statistics
get_backup_stats() {
    local uncompressed_count=$(find "${BACKUP_ROOT}" -name "backup_*.sql" -type f 2>/dev/null | wc -l)
    local compressed_count=$(find "${BACKUP_ROOT}" -name "backup_*.sql.gz" -type f 2>/dev/null | wc -l)
    local uncompressed_size=$(find "${BACKUP_ROOT}" -name "backup_*.sql" -type f -exec du -c {} + 2>/dev/null | tail -1 | awk '{print $1}')
    local compressed_size=$(find "${BACKUP_ROOT}" -name "backup_*.sql.gz" -type f -exec du -c {} + 2>/dev/null | tail -1 | awk '{print $1}')
    local metadata_count=$(find "${BACKUP_ROOT}" -name "*.metadata.json" -type f 2>/dev/null | wc -l)

    # Default to 0 if empty
    uncompressed_size=${uncompressed_size:-0}
    compressed_size=${compressed_size:-0}

    # Total backup directory size
    local total_size=$(du -sh "${BACKUP_ROOT}" 2>/dev/null | awk '{print $1}')
    local total_size_bytes=$(du -sb "${BACKUP_ROOT}" 2>/dev/null | awk '{print $1}')

    # Get filesystem capacity info
    local fs_usage=$(df "${BACKUP_ROOT}" 2>/dev/null | awk 'NR==2 {print $5}' | sed 's/%//')
    local fs_total=$(df "${BACKUP_ROOT}" 2>/dev/null | awk 'NR==2 {print $2}')
    local fs_available=$(df "${BACKUP_ROOT}" 2>/dev/null | awk 'NR==2 {print $4}')

    # Calculate compression ratio
    local total_uncompressed=$((uncompressed_size + compressed_size))
    local compression_ratio=0
    if [ $total_uncompressed -gt 0 ]; then
        compression_ratio=$((100 - (total_size_bytes * 100 / total_uncompressed)))
    fi

    echo "uncompressed_count=${uncompressed_count}"
    echo "compressed_count=${compressed_count}"
    echo "uncompressed_size=${uncompressed_size}"
    echo "compressed_size=${compressed_size}"
    echo "total_size=${total_size}"
    echo "total_size_bytes=${total_size_bytes}"
    echo "metadata_count=${metadata_count}"
    echo "fs_usage=${fs_usage}"
    echo "fs_total=${fs_total}"
    echo "fs_available=${fs_available}"
    echo "compression_ratio=${compression_ratio}"
}

# Calculate growth rate and predict exhaustion
predict_exhaustion() {
    local current_usage=$1
    local fs_total=$2

    # Read previous measurement from history
    if [ ! -f "${HISTORY_FILE}" ]; then
        return 0
    fi

    local prev_usage=$(python3 -c "import json; h = json.load(open('${HISTORY_FILE}')); print(h['measurements'][-1]['total_size_bytes'] if h.get('measurements') else 0)" 2>/dev/null || echo 0)
    local prev_timestamp=$(python3 -c "import json; h = json.load(open('${HISTORY_FILE}')); print(h['measurements'][-1]['timestamp'] if h.get('measurements') else 0)" 2>/dev/null || echo 0)

    if [ "$prev_usage" -eq 0 ] || [ -z "$prev_timestamp" ]; then
        return 0
    fi

    # Calculate growth rate (bytes per day)
    local time_diff=$(python3 -c "from datetime import datetime; print(int((datetime.now() - datetime.fromisoformat('${prev_timestamp}'.replace('Z', '+00:00'))).total_seconds() / 86400))" 2>/dev/null || echo 1)

    if [ $time_diff -lt 1 ]; then
        time_diff=1
    fi

    local usage_diff=$((current_usage - prev_usage))
    local growth_per_day=$((usage_diff / time_diff))

    # Only predict if growth is positive and significant
    if [ $growth_per_day -gt 0 ]; then
        local available_bytes=$((fs_total * 1024))
        local available_after_current=$((available_bytes - current_usage))
        local days_to_full=$((available_after_current / growth_per_day))

        if [ $days_to_full -gt 0 ] && [ $days_to_full -lt 365 ]; then
            local exhaustion_date=$(date -d "+${days_to_full} days" '+%Y-%m-%d')
            echo "${exhaustion_date}:${days_to_full}"
        fi
    fi
}

# Monitor backup disk usage
monitor_backups() {
    log_info "=========================================="
    log_info "Backup Disk Usage Monitoring"
    log_info "=========================================="

    # Get current statistics
    eval "$(get_backup_stats)"

    local total_backups=$((uncompressed_count + compressed_count))
    local compression_status="$uncompressed_count uncompressed, $compressed_count compressed"

    log_info "Backup Statistics:"
    log_info "  Total backups: ${total_backups}"
    log_info "  Uncompressed: ${uncompressed_count}, Compressed: ${compressed_count}"
    log_info "  Storage: ${total_size} (${total_size_bytes} bytes)"
    log_info "  Compression savings: ${compression_ratio}%"
    log_info "Filesystem Usage:"
    log_info "  Backup partition: ${fs_usage}% used"
    log_info "  Total capacity: ${fs_total} bytes"
    log_info "  Available space: ${fs_available} bytes"

    # Update history file
    python3 << 'PYEOF'
import json
import os
from datetime import datetime

history_file = os.environ.get('HISTORY_FILE', '')
if not history_file:
    exit(1)

# Read existing history or create new
if os.path.exists(history_file):
    with open(history_file, 'r') as f:
        try:
            history = json.load(f)
        except:
            history = {'measurements': []}
else:
    history = {'measurements': []}

# Ensure measurements list exists
if 'measurements' not in history:
    history['measurements'] = []

# Add new measurement
measurement = {
    'timestamp': datetime.utcnow().isoformat() + 'Z',
    'uncompressed_count': int(os.environ.get('uncompressed_count', 0)),
    'compressed_count': int(os.environ.get('compressed_count', 0)),
    'uncompressed_size': int(os.environ.get('uncompressed_size', 0)),
    'compressed_size': int(os.environ.get('compressed_size', 0)),
    'total_size_bytes': int(os.environ.get('total_size_bytes', 0)),
    'metadata_count': int(os.environ.get('metadata_count', 0)),
    'fs_usage_percent': int(os.environ.get('fs_usage', 0)),
    'fs_total_bytes': int(os.environ.get('fs_total', 0)),
    'fs_available_bytes': int(os.environ.get('fs_available', 0)),
    'compression_ratio': int(os.environ.get('compression_ratio', 0))
}

history['measurements'].append(measurement)

# Keep only last 90 days of measurements (once per day = 90 entries)
if len(history['measurements']) > 90:
    history['measurements'] = history['measurements'][-90:]

history['last_updated'] = datetime.utcnow().isoformat() + 'Z'

# Write updated history
with open(history_file, 'w') as f:
    json.dump(history, f, indent=2)
PYEOF

    # Check if thresholds are exceeded
    local alert_status=""
    local alert_message=""

    if [ "$fs_usage" -ge "$CRITICAL_THRESHOLD" ]; then
        alert_status="CRITICAL"
        alert_message="Backup partition is ${fs_usage}% full (CRITICAL threshold: ${CRITICAL_THRESHOLD}%)"
        log_error "${alert_message}"
        send_disk_notification "CRITICAL" "Backup partition usage: ${fs_usage}%

Backup Directory:
  Total size: ${total_size}
  Files: ${total_backups} backups
  Status: ${compression_status}

Filesystem:
  Used: ${fs_usage}%
  Available: ${fs_available} bytes
  Total: ${fs_total} bytes

Compression Ratio: ${compression_ratio}%

IMMEDIATE ACTION REQUIRED - Storage nearly exhausted!"
    elif [ "$fs_usage" -ge "$WARN_THRESHOLD" ]; then
        alert_status="WARNING"
        alert_message="Backup partition is ${fs_usage}% full (WARNING threshold: ${WARN_THRESHOLD}%)"
        log_warn "${alert_message}"
        send_disk_notification "WARNING" "Backup partition usage: ${fs_usage}%

Backup Directory:
  Total size: ${total_size}
  Files: ${total_backups} backups
  Status: ${compression_status}

Filesystem:
  Used: ${fs_usage}%
  Available: ${fs_available} bytes
  Total: ${fs_total} bytes

Compression Ratio: ${compression_ratio}%

Consider archiving or deleting old backups to free space."
    else
        alert_status="NORMAL"
        log_info "Disk usage within normal limits"
    fi

    log_info "=========================================="
    log_info "Status: ${alert_status}"
    log_info "=========================================="
}

# Initialize log directory
mkdir -p "${LOG_DIR}"

# Run monitor
log_info "Backup disk monitor started"
monitor_backups
exit_code=$?

log_info "Backup disk monitor completed (exit code: ${exit_code})"
exit $exit_code
