#!/usr/bin/env python3
"""
Maps Tracker Email Templates
Provides professional, clean email templates for notifications
"""

from datetime import datetime
import socket
import os


def get_server_info():
    """Get server hostname and timestamp"""
    hostname = socket.gethostname()
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return hostname, timestamp


def get_app_paths():
    """Get application paths dynamically"""
    # Get the base directory (scripts/email -> scripts -> project-root)
    script_dir = os.path.dirname(os.path.abspath(__file__))  # scripts/email
    base_dir = os.path.dirname(os.path.dirname(script_dir))  # project-root

    return {
        'base_dir': base_dir,
        'backups': os.path.join(base_dir, 'backups'),
        'logs': os.path.join(base_dir, 'logs'),
        'scripts_backup': os.path.join(base_dir, 'scripts/backup')
    }


def format_backup_success(backup_type, backup_file, backup_size, duration=None):
    """Format a successful backup notification email"""
    hostname, timestamp = get_server_info()

    body = f"""════════════════════════════════════════════════════════════════
DATABASE BACKUP COMPLETED SUCCESSFULLY - Maps Tracker
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          {hostname}
Environment:     Production
Status:          ✓ SUCCESS - Backup Completed
Timestamp:       {timestamp}

WHAT HAPPENED:
──────────────────────────────────────────────────────────────────
The scheduled database backup completed successfully. The Maps Tracker
database was backed up and verified for recovery capability.

BACKUP DETAILS:
──────────────────────────────────────────────────────────────────
Backup Type:     {backup_type.upper()}
Filename:        {os.path.basename(backup_file) if backup_file else 'N/A'}
File Size:       {backup_size}
"""

    if duration:
        body += f"Duration:        {duration}\n"

    body += f"""Checksum:        SHA256 (verified for integrity)

VERIFICATION COMPLETED:
──────────────────────────────────────────────────────────────────
✓ Database dump completed successfully
✓ Backup file verified and validated
✓ SHA256 checksum generated and stored
✓ Metadata created and indexed
✓ Backup added to catalog
✓ Archival policy applied (compressed if >30 days old)

BACKUP SCHEDULE:
──────────────────────────────────────────────────────────────────
• Full Backups:  Every Sunday at 2:00 AM
• Daily Backups: Every weekday (Mon-Sat) at 2:00 AM
• Verification:  Daily at 2:15 AM (integrity checks)
• Compression:   Daily at 3:00 AM (>30 days old)
• Cleanup:       Daily at 2:30 AM (>180 days old)
• Retention:     180 days (6 months minimum)

RECOVERY INFORMATION:
──────────────────────────────────────────────────────────────────
This backup can be used to restore the entire database if needed.
Restoration time: Typically 5-10 minutes depending on size
Recovery procedures: Documented and tested monthly

BUSINESS BENEFIT:
──────────────────────────────────────────────────────────────────
✓ Database protected against data loss
✓ Point-in-time recovery possible
✓ Disaster recovery capability verified
✓ Compliance with data protection policies

NEXT STEPS:
──────────────────────────────────────────────────────────────────
No action required. This is routine automated backup operation.
The backup system is fully operational and functioning normally.

SUPPORT INFORMATION:
──────────────────────────────────────────────────────────────────
For questions or issues:
  Contact: System Administrator / DevOps Team
  Log Location: {logs}/backup-manager.log
  Status: {timestamp}

════════════════════════════════════════════════════════════════
This is an automated notification from Maps Tracker Backup System.
All backups are stored securely with automated verification.
Generated by: Backup-Manager Process
"""
    return body


def format_backup_failure(backup_type, error_message, duration=None):
    """Format a failed backup notification email"""
    hostname, timestamp = get_server_info()

    body = f"""════════════════════════════════════════════════════════════════
DATABASE BACKUP FAILED - IMMEDIATE ACTION REQUIRED
Maps Tracker Backup System
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          {hostname}
Environment:     Production
Status:          ✗ FAILED - Backup Did Not Complete
Alert Severity:  HIGH - Recovery Capability At Risk
Timestamp:       {timestamp}

WHAT HAPPENED:
──────────────────────────────────────────────────────────────────
The scheduled database backup FAILED to complete successfully.
This means the database was NOT backed up and recovery capability
from this backup cycle is NOT available.

BACKUP DETAILS:
──────────────────────────────────────────────────────────────────
Backup Type:     {backup_type.upper()}
Error Message:   {error_message}
"""

    if duration:
        body += f"Duration:        {duration}\n"

    body += f"""
BUSINESS IMPACT:
──────────────────────────────────────────────────────────────────
⚠  No backup created for this cycle
⚠  Recovery point is one day old (or older)
⚠  If database fails now, up to 24 hours of data could be lost
⚠  SLA/Data protection policy is VIOLATED

IMMEDIATE ACTION REQUIRED (Follow in order):
──────────────────────────────────────────────────────────────────
1. ALERT TEAM IMMEDIATELY - Do not delay investigation
   Contact: System Administrator / DevOps Team

2. Check database is still running:
   docker compose ps | grep db
   Result should show: maps_db  (status: Up)

3. Verify disk space is available:
   df -h {backups}
   Required: At least 500MB free

4. Check backup directory exists and is writable:
   ls -lad {backups}
   Result: Should be drwxrwxr-x

5. Review detailed error logs:
   tail -100 {logs}/backup-manager.log | grep ERROR

6. Manually attempt backup immediately:
   {scripts_backup}/backup-manager.sh --daily

7. If manual backup succeeds: Problem is likely cron-related
   Check cron configuration: crontab -l | grep backup

8. If manual backup fails: Problem is system-related
   Check database health: docker compose exec db pg_isready
   Check for errors: docker compose logs db | tail -50

COMMON FAILURE REASONS:
──────────────────────────────────────────────────────────────────
• Database service is down or unresponsive
• Insufficient disk space on backup partition
• Backup directory permissions incorrect
• Network connectivity issues
• Cron job is not running properly
• Resource exhaustion (memory/CPU)

TROUBLESHOOTING CHECKLIST:
──────────────────────────────────────────────────────────────────
✓ Is database service running?
  docker compose exec db pg_isready

✓ Is database responding to connections?
  docker compose exec db psql -U \$POSTGRES_USER -d maps_tracker -c "SELECT 1"

✓ How much disk space is free?
  df -h | grep /backups

✓ Are backup files recent?
  ls -lt {backups}/*/*/*.sql | head -5

✓ Are there recent errors in logs?
  tail -50 {logs}/backup-manager.log

✓ Is the backup script executable?
  ls -la {scripts_backup}/backup-manager.sh

✓ Does cron have proper environment?
  env | grep POSTGRES

RESOLUTION PROCEDURE:
──────────────────────────────────────────────────────────────────
Step 1: Fix the root cause (use checklist above)
Step 2: Manually run backup to verify fix
Step 3: Check backup was created successfully
Step 4: Verify next scheduled backup runs on time
Step 5: Confirm backup integrity with verification

SUPPORT CONTACT:
──────────────────────────────────────────────────────────────────
Contact: System Administrator / DevOps Team
Priority: CRITICAL - Do not wait
Log Location: {logs}/backup-manager.log
Time To Resolve: ASAP (ideally within 2 hours)

════════════════════════════════════════════════════════════════
This is a critical alert. Database recovery capability is at risk.
Please resolve immediately and notify team when issue is fixed.
Generated by: Backup-Manager Process (Error Handler)
"""
    return body


def format_restore_success(restore_file, restore_duration, rows_restored=None):
    """Format a successful restore notification email"""
    hostname, timestamp = get_server_info()

    body = f"""════════════════════════════════════════════════════════════════
DATABASE RESTORE COMPLETED SUCCESSFULLY - Maps Tracker
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          {hostname}
Environment:     Production
Status:          ✓ SUCCESS - Database Restored
Timestamp:       {timestamp}

WHAT HAPPENED:
──────────────────────────────────────────────────────────────────
The database has been successfully restored from a backup. All data
from the backup timestamp is now active in the database. The system
is ready for normal operation.

RESTORE DETAILS:
──────────────────────────────────────────────────────────────────
Backup File:     {os.path.basename(restore_file) if restore_file else 'N/A'}
Restore Duration: {restore_duration}
"""

    if rows_restored:
        body += f"Rows Restored:   {rows_restored}\n"

    body += f"""
VERIFICATION COMPLETED:
──────────────────────────────────────────────────────────────────
✓ Backup file integrity verified
✓ Pre-restore safety backup created and stored
✓ Database restore completed successfully
✓ All tables and indexes restored
✓ Foreign key constraints validated
✓ Data consistency verified
✓ Application connectivity tested

POST-RESTORE STATUS:
──────────────────────────────────────────────────────────────────
✓ Database: ONLINE and OPERATIONAL
✓ Services: Running normally
✓ Data: Fully accessible
✓ Backups: Safety copy maintained
✓ System: Ready for production use

IMPORTANT INFORMATION:
──────────────────────────────────────────────────────────────────
• The original database state before restore is saved as a safety backup
• You can still recover to the previous state if needed
• All connections to the database are active
• Real-time backup and verification continue automatically
• The system is protected with new backup cycle started

NEXT STEPS:
──────────────────────────────────────────────────────────────────
1. Verify application functionality:
   - Test key user operations
   - Verify data accuracy
   - Check for missing or corrupted records

2. Monitor system behavior:
   - Watch application logs for errors
   - Monitor resource usage (CPU, Memory, Disk)
   - Verify backup schedule continues

3. Document restoration details:
   - Record restore timestamp
   - Document what was restored
   - Note any data inconsistencies found

4. If issues found:
   - Contact System Administrator immediately
   - Do not restore further until issue resolved

SUPPORT CONTACT:
──────────────────────────────────────────────────────────────────
If you need to restore to a different point in time:
  Contact: System Administrator / Database Team
  Procedure: Database Restore Process
  Recovery Point: Previous backup available if needed

Log Locations:
  - Restore Log: {logs}/restore-backup.log
  - Backup Log: {logs}/backup-manager.log

════════════════════════════════════════════════════════════════
Restoration completed successfully. Maps Tracker is operational.
Generated by: Database Restore Process
"""
    return body


def format_restore_failure(restore_file, error_message):
    """Format a failed restore notification email"""
    hostname, timestamp = get_server_info()

    body = f"""════════════════════════════════════════════════════════════════
DATABASE RESTORE FAILED - ACTION REQUIRED
Maps Tracker Backup System
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          {hostname}
Environment:     Production
Status:          ✗ FAILED - Database NOT Modified
Alert Severity:  HIGH - Immediate Action Required
Timestamp:       {timestamp}

WHAT HAPPENED:
──────────────────────────────────────────────────────────────────
The database restore operation FAILED and could not complete.
IMPORTANT: The database has NOT been modified - original data is intact.

RESTORE ATTEMPT DETAILS:
──────────────────────────────────────────────────────────────────
Backup File Attempted: {os.path.basename(restore_file) if restore_file else 'N/A'}
Error Message:        {error_message}

CRITICAL INFORMATION:
──────────────────────────────────────────────────────────────────
✓ Original database: UNCHANGED (restore did not execute)
✓ Safety backup: CREATED before restore attempt (preserved)
✓ Data loss: NOT OCCURRED
✓ System status: Previous state intact

BUSINESS IMPACT:
──────────────────────────────────────────────────────────────────
⚠  Database restoration was NOT completed
⚠  If database failure occurred, you CANNOT restore from this backup
⚠  Previous backup (if available) may still be used
⚠  Investigate cause immediately to prevent future restore failures

IMMEDIATE ACTION REQUIRED (Follow in order):
──────────────────────────────────────────────────────────────────
1. ALERT TEAM IMMEDIATELY:
   Contact: Database Administrator / System Administrator
   Priority: HIGH - Address within 1 hour

2. Verify database is still operational:
   docker compose exec db pg_isready
   Should return: "accepting connections"

3. Review detailed error logs:
   tail -100 {logs}/restore-backup.log | grep ERROR
   tail -50 {logs}/error.log

4. Verify backup file is accessible and valid:
   ls -lh {os.path.basename(restore_file) if restore_file else '[backup_location]'}
   file {os.path.basename(restore_file) if restore_file else '[backup_location]'}
   pg_restore --list {os.path.basename(restore_file) if restore_file else '[backup_location]'} | head

5. Check system resources:
   docker compose exec db df -h
   docker stats
   free -h

6. Verify database integrity:
   docker compose exec db psql -U \$POSTGRES_USER -d maps_tracker -c "SELECT version();"
   docker compose exec db psql -U \$POSTGRES_USER -d maps_tracker -c "\\dt"

COMMON RESTORE FAILURE REASONS:
──────────────────────────────────────────────────────────────────
• Database service crashed or restarted during restore
• Insufficient disk space for restore operation
• Backup file is corrupted or unreadable
• Database user lacks required permissions
• Backup format is incompatible with current PostgreSQL version
• Network issues during restore process
• Resource exhaustion (out of memory)

TROUBLESHOOTING CHECKLIST:
──────────────────────────────────────────────────────────────────
✓ Is database service running?
  docker compose ps | grep db

✓ Is database accepting connections?
  docker compose exec db pg_isready

✓ How much disk space is available?
  docker compose exec db df -h | grep var

✓ Is the backup file readable?
  file [backup_file]
  pg_restore --list [backup_file] | wc -l

✓ What version of PostgreSQL is running?
  docker compose exec db psql --version

✓ Are there permission issues?
  docker compose exec db psql -l

✓ Are memory/CPU available?
  docker stats

RECOVERY OPTIONS:
──────────────────────────────────────────────────────────────────
1. Try using a different (older) backup:
   ls -lt {backups}/*/*/*.sql
   ./scripts/backup/restore-backup.sh --file [older_backup]

2. Increase available resources and retry:
   - Stop non-critical services
   - Clear disk space
   - Restart database: docker compose restart db
   - Retry restore

3. Request fallback to previous state:
   - Contact: Database Administrator
   - Fallback method: Recovery from safety backup

SUPPORT CONTACT:
──────────────────────────────────────────────────────────────────
Contact: Database Administrator / DevOps Team
Priority: HIGH - Resolve within 1-2 hours
Log Locations:
  - Restore Log: {logs}/restore-backup.log
  - Error Log: {logs}/error.log
  - Database Log: docker compose logs db

════════════════════════════════════════════════════════════════
Database is SAFE - original data intact. Investigate cause before
retrying restore. Contact support if issue persists.
Generated by: Database Restore Process (Error Handler)
"""
    return body


def format_remote_sync_success(backup_count, total_size, duration, remote_host):
    """Format a successful remote backup sync notification email"""
    hostname, timestamp = get_server_info()

    body = f"""MAPS TRACKER - REMOTE BACKUP SYNC SUCCESS NOTIFICATION
════════════════════════════════════════════════════════════════

Status:     ✓ SUCCESSFUL
Date:       {timestamp}
Server:     {hostname}

SYNC DETAILS
──────────────────────────────────────────────────────────────────
Remote Host:     {remote_host}
Backups Synced:  {backup_count}
Total Size:      {total_size}
Duration:        {duration}

VERIFICATION
──────────────────────────────────────────────────────────────────
✓ SSH connection successful
✓ Remote directories created/verified
✓ All backup files synced successfully
✓ File integrity verified with checksums
✓ Remote storage updated

REMOTE BACKUP STATUS
──────────────────────────────────────────────────────────────────
• Backups are now replicated to the remote server
• Offsite backup protection active
• Disaster recovery capability enabled
• All checksums verified for integrity

SCHEDULE
──────────────────────────────────────────────────────────────────
Remote backups are automatically synced:
• After each full backup (Sundays at 2:00 AM)
• After each daily backup (Daily at 2:00 AM)
• Before any scheduled maintenance

════════════════════════════════════════════════════════════════
Your data is now protected at multiple locations.
This is an automated notification from the Maps Tracker Backup System.
"""
    return body


def format_remote_sync_failure(error_message, remote_host):
    """Format a failed remote backup sync notification email"""
    hostname, timestamp = get_server_info()

    body = f"""MAPS TRACKER - REMOTE BACKUP SYNC FAILURE NOTIFICATION
════════════════════════════════════════════════════════════════

Status:     ✗ FAILED
Date:       {timestamp}
Server:     {hostname}

SYNC DETAILS
──────────────────────────────────────────────────────────────────
Remote Host:     {remote_host}
Error:           {error_message}

ACTION REQUIRED
──────────────────────────────────────────────────────────────────
⚠ Remote backup synchronization failed. Local backups are safe.
The remote location is NOT up-to-date with recent backups.

Please verify:
1. Remote host is reachable (ping {remote_host})
2. SSH connection is working (check SSH keys)
3. Remote storage has sufficient space (df on remote)
4. Network connectivity to remote host
5. Remote user credentials are valid

TROUBLESHOOTING
──────────────────────────────────────────────────────────────────
Test SSH connection:
  ssh -v {remote_host} echo "SSH connection test"

Check rsync connectivity:
  rsync --list-only {remote_host}:~/maps-tracker-backup/

View detailed error log:
  tail -50 logs/rsync-backup.log | grep ERROR

BACKUP STATUS
──────────────────────────────────────────────────────────────────
✓ Local backups: Still being created and stored locally
✓ Remote backups: Out of sync (last successful sync unknown)
⚠ Offsite protection: Currently unavailable

════════════════════════════════════════════════════════════════
Please resolve the connectivity issue to restore remote backup protection.
For support, review logs/rsync-backup.log for detailed error information.
"""
    return body


def format_monthly_restore_test_success(backup_used, test_duration, rows_verified):
    """Format a successful monthly restore test notification email"""
    hostname, timestamp = get_server_info()

    body = f"""MAPS TRACKER - MONTHLY RESTORE TEST SUCCESS NOTIFICATION
════════════════════════════════════════════════════════════════

Status:     ✓ SUCCESSFUL
Date:       {timestamp}
Server:     {hostname}

TEST SUMMARY
──────────────────────────────────────────────────────────────────
Backup Used:     {os.path.basename(backup_used) if backup_used else 'Latest'}
Test Duration:   {test_duration}
Rows Verified:   {rows_verified}

VERIFICATION RESULTS
──────────────────────────────────────────────────────────────────
✓ Backup file selected and validated
✓ Test database created successfully
✓ Database restore completed without errors
✓ All tables and indexes verified
✓ Data integrity checks passed
✓ Sample queries executed successfully:
  - Vehicle location retrieval
  - Location count aggregation
  - Places of interest query
  - User data consistency
✓ Test database cleaned up

DISASTER RECOVERY STATUS
──────────────────────────────────────────────────────────────────
✓ Backups are valid and restorable
✓ Recovery procedures verified and working
✓ RTO (Recovery Time Objective): Confirmed achievable
✓ Database integrity: Confirmed
✓ Data completeness: Confirmed

MONTHLY TEST CONCLUSION
──────────────────────────────────────────────────────────────────
All monthly restore tests have passed successfully.
Your backup and recovery procedures are fully operational.
Data restoration capability is verified and ready.

════════════════════════════════════════════════════════════════
This is a routine automated test confirming system reliability.
Your data protection and recovery procedures are working correctly.
"""
    return body


def format_monthly_restore_test_failure(error_message, backup_attempted):
    """Format a failed monthly restore test notification email"""
    hostname, timestamp = get_server_info()

    body = f"""MAPS TRACKER - MONTHLY RESTORE TEST FAILURE NOTIFICATION
════════════════════════════════════════════════════════════════

Status:     ✗ FAILED
Date:       {timestamp}
Server:     {hostname}

TEST DETAILS
──────────────────────────────────────────────────────────────────
Backup Attempted:     {os.path.basename(backup_attempted) if backup_attempted else 'Latest'}
Error:                {error_message}

ISSUE IDENTIFIED
──────────────────────────────────────────────────────────────────
⚠ The monthly restore test failed. This indicates a potential problem
with disaster recovery procedures that requires immediate investigation.

What this means:
• Current backups may not be restorable
• Recovery procedures are not functioning correctly
• Data recovery might not be possible in case of disaster

ACTION REQUIRED
──────────────────────────────────────────────────────────────────
1. Investigate immediately:
   tail -100 logs/backup-manager.log | grep ERROR
   tail -100 logs/restore-backup.log | grep ERROR

2. Verify backup integrity:
   ls -lh backups/full/*/backup_*.sql
   file backups/full/*/backup_*.sql

3. Test database connectivity:
   docker compose exec db pg_isready
   docker compose exec db pg_restore --list /backups/backup_*.sql

4. Check disk space:
   df -h

5. Verify permissions:
   ls -la backups/ logs/

IMPACT ASSESSMENT
──────────────────────────────────────────────────────────────────
Backup Creation:    Active (continuing)
Backup Integrity:   Questionable (test failed)
Recovery Capability: Not verified
Risk Level:         HIGH

════════════════════════════════════════════════════════════════
This is a critical notification. Please resolve the issue immediately
to restore confidence in your disaster recovery procedures.
Contact your system administrator for immediate assistance.
"""
    return body
