#!/bin/bash
#
# Backup Deduplication Script
# Identifies and optimizes duplicate backups using hard linking
#
# Features:
#   - Compares backup files by SHA256 checksum
#   - Creates hard links for identical backups (saves storage)
#   - Maintains metadata for all linked backups
#   - Generates deduplication report
#   - Tracks storage savings
#

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$(dirname "${SCRIPT_DIR}")")"
BACKUP_ROOT="${BASE_DIR}/backups"
LOG_DIR="${BASE_DIR}/logs"
DEDUP_LOG="${LOG_DIR}/backup-deduplication.log"
INDEX_FILE="${BACKUP_ROOT}/index/backup_index.json"

# Load .env if it exists for environment variables
if [ -f "${BASE_DIR}/.env" ]; then
    set +a
    source "${BASE_DIR}/.env"
    set -a
fi

# Email settings
EMAIL_ENABLED="${BACKUP_EMAIL_ENABLED:-true}"
EMAIL_RECIPIENT="${BACKUP_EMAIL:-admin@example.com}"
EMAIL_SUBJECT_PREFIX="[Maps Tracker Backup Deduplication]"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Logging functions
log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[${timestamp}] [${level}] ${message}" | tee -a "${DEDUP_LOG}"
}

log_info() {
    log "INFO" "$@"
    echo -e "${GREEN}[INFO]${NC} $@"
}

log_warn() {
    log "WARN" "$@"
    echo -e "${YELLOW}[WARN]${NC} $@"
}

log_error() {
    log "ERROR" "$@"
    echo -e "${RED}[ERROR]${NC} $@" >&2
}

# Send email notification
send_dedup_notification() {
    local status=$1
    local details=$2

    if [ "$EMAIL_ENABLED" != "true" ]; then
        return 0
    fi

    local subject="${EMAIL_SUBJECT_PREFIX} Report - ${status^^}"

    local email_body="════════════════════════════════════════════════════════════════
BACKUP DEDUPLICATION REPORT - Maps Tracker
════════════════════════════════════════════════════════════════

Application:     Maps Tracker (Vehicle Tracking System)
Company:         [YOUR COMPANY NAME]
Server:          $(hostname)
Environment:     Production
Process:         Weekly Backup Deduplication (Hard-linking)
Status:          ${status}
Timestamp:       $(date '+%Y-%m-%d %H:%M:%S')

WHAT HAPPENED:
──────────────────────────────────────────────────────────────────
The automated deduplication process ran to identify and optimize
identical backup files. Hard links are created to reduce storage
waste from duplicate backups without affecting recoverability.

TECHNICAL DETAILS:
──────────────────────────────────────────────────────────────────
• Process: Content-addressable storage via SHA256 checksums
• Method: Hard linking identical backup files
• Benefit: Saves storage without reducing recovery capability
• Frequency: Every Sunday at 1:00 AM (before full backup)

DEDUPLICATION RESULTS:
──────────────────────────────────────────────────────────────────
${details}

IMPORTANT INFORMATION:
──────────────────────────────────────────────────────────────────
✓ Hard links point to same data blocks (no redundancy)
✓ All backups remain fully recoverable
✓ Deleting one hard-linked file keeps others intact
✓ Space savings shown only if files actually duplicated

NEXT STEPS:
──────────────────────────────────────────────────────────────────
No action required if status is SUCCESS or NO ACTION NEEDED.
Check logs if unexpected results occur.

SUPPORT CONTACT:
──────────────────────────────────────────────────────────────────
For questions or issues, contact: System Administrator
Log Location: /home/devnan/effective-guide/logs/backup-deduplication.log

════════════════════════════════════════════════════════════════
This is an automated notification from Maps Tracker backup system.
Generated by: Backup Deduplication Process (Weekly)"

    # Try using the SMTP relay script
    local SEND_EMAIL_SCRIPT="${BASE_DIR}/scripts/email/send-email.sh"
    if [ -f "${SEND_EMAIL_SCRIPT}" ]; then
        "${SEND_EMAIL_SCRIPT}" "$EMAIL_RECIPIENT" "$subject" "$email_body" 2>&1
        return $?
    fi

    # Fallback to mail command if available
    if command -v mail &> /dev/null || command -v mailx &> /dev/null; then
        local MAIL_CMD="mail"
        if command -v mailx &> /dev/null; then
            MAIL_CMD="mailx"
        fi
        echo "$email_body" | $MAIL_CMD -s "$subject" "$EMAIL_RECIPIENT" 2>&1
        return $?
    fi

    return 1
}

# Read backup checksums from index
read_backup_checksums() {
    python3 << 'PYEOF'
import json
import os

index_file = os.environ.get('INDEX_FILE', '')
if not index_file or not os.path.exists(index_file):
    exit(1)

try:
    with open(index_file, 'r') as f:
        index = json.load(f)

    # Create checksum -> backup mapping
    checksums = {}
    for backup in index['backups']:
        checksum = backup.get('checksum_sha256', '')
        backup_file = backup.get('backup_file', '')
        relative_path = backup.get('relative_path', '')

        if checksum and backup_file:
            if checksum not in checksums:
                checksums[checksum] = []
            checksums[checksum].append({
                'backup_file': backup_file,
                'relative_path': relative_path,
                'full_path': os.path.join(os.environ.get('BACKUP_ROOT', ''), relative_path) if relative_path else ''
            })

    # Output duplicate groups (checksums with more than one backup)
    for checksum, backups in checksums.items():
        if len(backups) > 1:
            print(f"DUPLICATE:{checksum}:{len(backups)}")
            for backup in backups:
                print(f"  {backup['full_path']}")

except Exception as e:
    print(f"Error reading backup index: {e}", file=__import__('sys').stderr)
    exit(1)
PYEOF
}

# Deduplicate backups using hard links
deduplicate_backups() {
    log_info "=========================================="
    log_info "Backup Deduplication"
    log_info "=========================================="

    local duplicates_found=0
    local hardlinks_created=0
    local space_saved=0

    # Read backup checksums
    local checksum_output=$(read_backup_checksums)

    if [ -z "$checksum_output" ]; then
        log_info "No duplicate backups detected"
        return 0
    fi

    # Process duplicate groups
    echo "$checksum_output" | while IFS=: read -r type checksum count rest; do
        if [ "$type" != "DUPLICATE" ]; then
            continue
        fi

        ((duplicates_found++))
        log_info "Found $count identical backups (checksum: ${checksum:0:16}...)"

        # Get the primary file (first one, by timestamp)
        local primary_file=""
        echo "$checksum_output" | grep -A $((count)) "^DUPLICATE:${checksum}:" | tail -n +2 | sort | head -1 | xargs -I {} basename {} | while read primary; do
            primary_file="${BACKUP_ROOT}/${primary}"

            # Create hard links for other identical backups
            echo "$checksum_output" | grep -A $((count)) "^DUPLICATE:${checksum}:" | tail -n +2 | sort | tail -n +2 | while read dup_file; do
                dup_path="${BACKUP_ROOT}/${dup_file}"

                if [ "$dup_file" = "$primary" ]; then
                    continue
                fi

                # Check if already a hard link to the same inode
                if [ -f "$dup_path" ] && [ -f "$primary_file" ]; then
                    primary_inode=$(stat -c %i "$primary_file" 2>/dev/null || stat -f %i "$primary_file")
                    dup_inode=$(stat -c %i "$dup_path" 2>/dev/null || stat -f %i "$dup_path")

                    if [ "$primary_inode" = "$dup_inode" ]; then
                        log_info "  ⊗ Already linked: $(basename $dup_path)"
                        continue
                    fi

                    # Get size before deduplication
                    local size_before=$(stat -c%s "$dup_path" 2>/dev/null || stat -f%z "$dup_path")

                    # Create hard link by removing duplicate and creating link
                    if rm -f "$dup_path" && ln "$primary_file" "$dup_path"; then
                        ((hardlinks_created++))
                        space_saved=$((space_saved + size_before))
                        log_info "  ✓ Hard linked: $(basename $dup_path)"
                    else
                        log_warn "  ⚠ Failed to create hard link for $dup_path"
                    fi
                fi
            done
        done
    done

    log_info "=========================================="
    log_info "Deduplication Summary"
    log_info "=========================================="
    log_info "Duplicate groups found: ${duplicates_found}"
    log_info "Hard links created: ${hardlinks_created}"

    if [ $hardlinks_created -gt 0 ]; then
        local space_saved_human=$(numfmt --to=iec-i --suffix=B "${space_saved}" 2>/dev/null || echo "${space_saved} bytes")
        log_info "Storage space saved: ${space_saved_human}"

        # Send success notification
        local email_details="Deduplication completed successfully.

Duplicates Found: ${duplicates_found}
Hard Links Created: ${hardlinks_created}
Storage Saved: ${space_saved_human}

Note: Hard links do not reduce disk usage but ensure that
identical backups share the same inode, improving efficiency."

        send_dedup_notification "SUCCESS" "${email_details}"
    else
        log_info "No deduplication opportunities found"
        send_dedup_notification "NO ACTION NEEDED" "All backups are unique or already deduplicated."
    fi
}

# Initialize log directory
mkdir -p "${LOG_DIR}"

# Run deduplication
log_info "Deduplication job started"
deduplicate_backups
exit_code=$?

log_info "Deduplication job completed (exit code: ${exit_code})"
exit $exit_code
