"""Initial migration with all tables including api_token

Revision ID: 211704bace94
Revises: 
Create Date: 2025-12-09 13:53:49.697731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211704bace94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('idx_vehicles_api_token')
        batch_op.drop_constraint('vehicles_api_token_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_vehicles_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_api_token'))
        batch_op.create_unique_constraint('vehicles_api_token_key', ['api_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('idx_vehicles_api_token', ['api_token'], unique=False)

    # ### end Alembic commands ###
